addSbtPlugin("com.gradle" % "sbt-develocity" % "1.3")
addSbtPlugin("com.github.sbt" % "sbt-dynver" % "5.1.0")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.2.1")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("com.gradle" % "sbt-develocity-common-custom-user-data" % "1.3")
